name: CI/CD - Deploy using existing Docker image

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull existing image aichatbot-ui
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/aichatbot-ui:latest

    - name: Re-tag it as cloneaichatbot
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/aichatbot-ui:latest ${{ secrets.DOCKERHUB_USERNAME }}/cloneaichatbot:latest

    - name: Push re-tagged image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloneaichatbot:latest

    - name: Deploy to Production Server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_SSH_HOST }}
        username: ${{ secrets.PROD_SSH_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        port: ${{ secrets.PROD_SSH_PORT || '22' }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cloneaichatbot:latest
          docker stop chatbot-ui || true
          docker rm chatbot-ui || true
          docker run -d -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} --name chatbot-ui -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/cloneaichatbot:latest
