name: CI/CD - Build and Deploy Chatbot

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chatbot-ui:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/chatbot-ui:latest

    - name: Deploy to Production Server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_SSH_HOST }}
        username: ${{ secrets.PROD_SSH_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        port: ${{ secrets.PROD_SSH_PORT || '22' }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/chatbot-ui:latest
          docker stop chatbot-ui || true
          docker rm chatbot-ui || true
          docker run -d --name chatbot-ui -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/chatbot-ui:latest
